name: test

on:
  push:
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: test
      run: make test
    - name: test output
      if: always()
      run: cat build/Testing/Temporary/LastTest.log
  test-macos:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: test
      run: make test
    - name: test output
      if: always()
      run: cat build/Testing/Temporary/LastTest.log
  test-mingw:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: test
      run: make test
    - name: test output
      if: always()
      run: cat build/Testing/Temporary/LastTest.log
  test-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0
    - name: test
      run: make test-msvc
    - name: test output
      if: always()
      run: cat build/Testing/Temporary/LastTest.log
